### PR TITLE
feat: greatly improve debugging

### PR DESCRIPTION
**Pull request by NanderTGA**
This pull requests contains the announced changes to the debug window.
Also fixes this bug where some logs would have the folder name and the file name switched around.

### CODE REVIEW

**Comment by GittyMac** [comment]
Looks fine, although the CLogger section would probably need a better implementation later on.

**Comment by NanderTGA** [comment]
The CLogger section is hard to improve upon, as LocalConnection is for communication between SWFs.
This will require some messing with either main.swf or creating a new one which loads main.swf and does the LocalConnection things.

**Comment by NanderTGA** [comment]
Or messing with a small SWF.

**Comment by NanderTGA** [comment]
Might also be worth mentioning the debug window now supports resizing.

**Pull request merged**
